/*
 * Jessica Qiao
 * 09/10/2018
 */

/**
 *
 * @author shqia0005
 */
public class makingapizza extends javax.swing.JFrame {
    

    /**
     * Creates new form makingapizza
     */
    public makingapizza() {
        
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictures1 = new javax.swing.JLabel();
        pictures2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        enterdiameter = new javax.swing.JTextField();
        calc = new javax.swing.JButton();
        subtotal = new javax.swing.JLabel();
        taxes = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        output_subtotal = new javax.swing.JLabel();
        output_taxes = new javax.swing.JLabel();
        output_grandtotal = new javax.swing.JLabel();
        output_sentence = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pictures1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipe-26056_Medium_ID-1532520.jpg"))); // NOI18N

        pictures2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N

        title.setFont(new java.awt.Font("AlgerianBasDEE", 0, 30)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 255));
        title.setText("Putrid Pizza");

        instruction.setFont(new java.awt.Font("AachenDEEMed", 0, 22)); // NOI18N
        instruction.setForeground(new java.awt.Color(255, 51, 51));
        instruction.setText("Enter the diameter of pizza(cm)");

        enterdiameter.setText("0");

        calc.setBackground(new java.awt.Color(0, 102, 102));
        calc.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        calc.setForeground(new java.awt.Color(0, 102, 102));
        calc.setText("CALCULATE NOW!!");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });

        subtotal.setFont(new java.awt.Font("AachenDEEMed", 0, 18)); // NOI18N
        subtotal.setForeground(new java.awt.Color(255, 0, 102));
        subtotal.setText("Subtotal ($) :");

        taxes.setFont(new java.awt.Font("AachenDEEMed", 0, 18)); // NOI18N
        taxes.setForeground(new java.awt.Color(255, 0, 102));
        taxes.setText("Taxes ($) :");

        grandtotal.setFont(new java.awt.Font("AachenDEEMed", 0, 18)); // NOI18N
        grandtotal.setForeground(new java.awt.Color(255, 0, 102));
        grandtotal.setText("Grand Total ($) :");

        output_subtotal.setFont(new java.awt.Font("AachenDEEMed", 0, 12)); // NOI18N
        output_subtotal.setForeground(new java.awt.Color(255, 102, 102));

        output_taxes.setFont(new java.awt.Font("AachenDEEMed", 0, 12)); // NOI18N
        output_taxes.setForeground(new java.awt.Color(255, 102, 102));

        output_grandtotal.setFont(new java.awt.Font("AachenDEEMed", 0, 12)); // NOI18N
        output_grandtotal.setForeground(new java.awt.Color(255, 102, 102));

        output_sentence.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        output_sentence.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(grandtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(output_grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(output_taxes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(output_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output_sentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pictures1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(title)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pictures2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(instruction)
                                        .addGap(18, 18, 18)
                                        .addComponent(enterdiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(calc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pictures1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pictures2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterdiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calc)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(output_subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxes)
                            .addComponent(output_taxes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(grandtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(output_grandtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(output_sentence, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        double price_labour_and_pizzashop, price_per_diameter, price_per_pizza, taxes, subtotal, grandtotal;
        int diameter;
        double tax = 0.13;
        diameter = Integer.parseInt(enterdiameter.getText());
        price_per_diameter = 0.5;
        price_labour_and_pizzashop = 1.74;
        price_per_pizza = price_per_diameter * diameter;
        
        subtotal = price_per_pizza + price_labour_and_pizzashop;
        subtotal = subtotal * 100;
        subtotal = Math.round (subtotal);
        subtotal = subtotal / 100;
        
        taxes = (price_labour_and_pizzashop + price_per_pizza) * tax;
        taxes = taxes * 100;
        taxes = Math.round (taxes);
        taxes = taxes / 100;
        
        grandtotal = subtotal + taxes;
        grandtotal = grandtotal * 100;
        grandtotal = Math.round (grandtotal);
        grandtotal = grandtotal / 100;
        
        
        output_subtotal.setText( String.valueOf(subtotal));
        output_taxes.setText( String.valueOf(taxes));
        output_grandtotal.setText( String.valueOf(grandtotal));
        
        
        if (diameter > 1 && diameter < 15){
            output_sentence.setText("We are going to make you a cute little pizza!");
        }
        else if (diameter > 20 && diameter < 40){
            output_sentence.setText("This will be delicious!");
        }
      
        else if (diameter > 40){
            output_sentence.setText("Whoa, big pizza! You might need a truck to get this home!");
        }
        
    }//GEN-LAST:event_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makingapizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc;
    private javax.swing.JTextField enterdiameter;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel output_grandtotal;
    private javax.swing.JLabel output_sentence;
    private javax.swing.JLabel output_subtotal;
    private javax.swing.JLabel output_taxes;
    private javax.swing.JLabel pictures1;
    private javax.swing.JLabel pictures2;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel taxes;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
